/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OilDistribution;

/**
 *
 * @author Admin
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Suppliers extends javax.swing.JFrame {

    /**
     * Creates new form Suppliers
     */
    
    public Suppliers() {
        initComponents();
        getConnection();
        loadSuppliers();
    
    stable.addMouseListener(new java.awt.event.MouseAdapter(){
        public void mouseClicked(java.awt.event.MouseEvent evt){
            stableMouseClicked(evt);
      } 
    });
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        stable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        supplierid = new javax.swing.JTextField();
        suppliername = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        contactperson = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        editsuppliers = new javax.swing.JButton();
        addsuppliers = new javax.swing.JButton();
        deletesuppliers = new javax.swing.JButton();
        refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SUPPLIERS");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        stable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SupplierID", "SupplierName", "Location", "ContactPerson", "Phone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        stable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stable);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("SupplierID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("SupplierName");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Location");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ContactPerson");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Phone");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Email");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supplierid, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(suppliername)
                    .addComponent(location)
                    .addComponent(contactperson)
                    .addComponent(phone)
                    .addComponent(email))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(supplierid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(suppliername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(contactperson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        editsuppliers.setText("Edit Suppliers");
        editsuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editsuppliersActionPerformed(evt);
            }
        });

        addsuppliers.setText("Add Suppliers");
        addsuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsuppliersActionPerformed(evt);
            }
        });

        deletesuppliers.setText("Delete Suppliers");
        deletesuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesuppliersActionPerformed(evt);
            }
        });

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deletesuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editsuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addsuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(289, 289, 289))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addsuppliers)
                .addGap(47, 47, 47)
                .addComponent(editsuppliers)
                .addGap(47, 47, 47)
                .addComponent(deletesuppliers)
                .addGap(46, 46, 46)
                .addComponent(refresh)
                .addGap(175, 175, 175))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addsuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsuppliersActionPerformed
        // TODO add your handling code here:
        try {
        String name = suppliername.getText();
        String loc = location.getText();
        String contact = contactperson.getText();
        String ph = phone.getText();
        String em = email.getText();

        Connection con = getConnection();
        PreparedStatement ps = con.prepareStatement(
            "INSERT INTO suppliers (suppliername, location, contact, phone, email) VALUES (?,?,?,?,?)");
        ps.setString(1, name);     // Corresponds to suppliername
        ps.setString(2, loc);      // Corresponds to location
        ps.setString(3, contact);  // Corresponds to contactperson
        ps.setString(4, ph);       // Corresponds to phone
        ps.setString(5, em);       // Corresponds to email
        
        ps.executeUpdate();
        con.close();

        JOptionPane.showMessageDialog(null, "Supplier added successfully!");

        // Clear fields
        supplierid.setText("");
        suppliername.setText("");
        location.setText("");
        contactperson.setText("");
        phone.setText("");
        email.setText("");

        loadSuppliers();

    } catch(Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_addsuppliersActionPerformed

    private void editsuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editsuppliersActionPerformed
        // TODO add your handling code here:
        String idText = supplierid.getText().trim();
        
        // 1. Validate the SupplierID field
        if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the Supplier ID to edit.", "Input Error", JOptionPane.WARNING_MESSAGE);
        return; // Stop execution if validation fails
    }
        try { 
        int id = Integer.parseInt(idText);
        String name = suppliername.getText();
        String loc = location.getText();
        String contact = contactperson.getText();
        String ph = phone.getText();
        String em = email.getText();

        Connection con = getConnection();
        PreparedStatement ps = con.prepareStatement(
            "UPDATE suppliers SET suppliername=?, location=?, contact=?, phone=?, email=? WHERE supplierid=?"
        );
        ps.setString(1, name);
        ps.setString(2, loc);
        ps.setString(3, contact);
        ps.setString(4, ph);
        ps.setString(5, em);
        ps.setInt(6, id);
        
        ps.executeUpdate();
        con.close();

        JOptionPane.showMessageDialog(null, "Supplier updated successfully!");

        // Clear fields
        supplierid.setText("");
        suppliername.setText("");
        location.setText("");
        contactperson.setText("");
        phone.setText("");
        email.setText("");

        loadSuppliers();

    } catch(Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_editsuppliersActionPerformed

    private void deletesuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesuppliersActionPerformed
        // TODO add your handling code here:
        String idText = supplierid.getText().trim();
    
    // 1. Check if the ID field is empty (meaning no row was selected)
    if (idText.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a supplier from the table to delete.", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return; 
    }
    try {
        int id = Integer.parseInt(idText);

        // 2. Confirmation dialog
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete supplier ID " + id + "?", 
            "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            
            // --- 3. Database Deletion ---
            // Use the getConnection() method you already have for consistency
            java.sql.Connection conn = getConnection(); 
            if (conn == null) return; // Exit if connection failed
    
        String sql = "DELETE FROM suppliers WHERE supplierid=?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        pst.setInt(1, id);

        pst.executeUpdate();
        conn.close();

        javax.swing.JOptionPane.showMessageDialog(this, "Supplier Deleted!");
        loadSuppliers();

        // Clear fields
        supplierid.setText("");
        suppliername.setText("");
        location.setText("");
        contactperson.setText("");
        phone.setText("");
        email.setText("");
        }
    } 
        catch(java.lang.NumberFormatException nfe) {
        // Safety catch if the user manually tampered with the ID field
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Invalid Supplier ID format.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
        catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
      }
    }//GEN-LAST:event_deletesuppliersActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        loadSuppliers();
    }//GEN-LAST:event_refreshActionPerformed

    private void stableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stableMouseClicked
        // TODO add your handling code here:
        // Get the model and the index of the selected row
        DefaultTableModel model = (DefaultTableModel) stable.getModel();
        int selectedRowIndex = stable.getSelectedRow();
        
        //if a row is actually selected
        if (selectedRowIndex != -1) {
            // Read the values from the selected table row
            String id = model.getValueAt(selectedRowIndex, 0).toString();
            String name = model.getValueAt(selectedRowIndex, 1).toString();
            String loc = model.getValueAt(selectedRowIndex, 2).toString();
            String contact = model.getValueAt(selectedRowIndex, 3).toString();
            String phoneNum = model.getValueAt(selectedRowIndex, 4).toString();
            String mail = model.getValueAt(selectedRowIndex, 5).toString();
             
            // Set the text fields with the selected data
            supplierid.setText(id);
            suppliername.setText(name);
            location.setText(loc);
            contactperson.setText(contact);
            phone.setText(phoneNum);
            email.setText(mail);

        }
    }//GEN-LAST:event_stableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suppliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addsuppliers;
    private javax.swing.JTextField contactperson;
    private javax.swing.JButton deletesuppliers;
    private javax.swing.JButton editsuppliers;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField location;
    private javax.swing.JTextField phone;
    private javax.swing.JButton refresh;
    private javax.swing.JTable stable;
    private javax.swing.JTextField supplierid;
    private javax.swing.JTextField suppliername;
    // End of variables declaration//GEN-END:variables

    
    public void loadSuppliers() {
 try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection(
            "jdbc:mysql://localhost/oildb", "root", ""
        );
        
        String sql = "SELECT * FROM suppliers";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) stable.getModel();
        model.setRowCount(0); // clear table

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("supplierid"),
                rs.getString("suppliername"),
                rs.getString("location"),
                rs.getString("contact"),
                rs.getString("phone"),
                rs.getString("email")
            });
        }

        conn.close();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}


    private Connection getConnection() {
        try{
            return DriverManager.getConnection("jdbc:mysql://localhost/oildb", "root", "");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
    }
}
